# Generated by Django 3.2.5 on 2021-08-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_user',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
