# Generated by Django 3.2.5 on 2021-08-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user_administrador',
            new_name='is_staff',
        ),
    ]
